// const path = require("path");

async function deployContract() {
    if (network.name !== "localhost") {
        throw new Error(
            `\n*** You are running against network: [ ${network.name} ]\n` +
            "*** Pending further development, please run only against localhost.\n" +
            "*** Try again with\n" +
            "***     `npx hardhat run <SCRIPT_FILE_PATH> --network localhost`"
        );
    }

    const signers = await ethers.getSigners();

    const deployer = signers[19]; // use the last of the 20 accounts generated by hardhat

    const myGameTokenContractFactory =
        await ethers.getContractFactory(
            "MyGameToken",
            deployer
        );

    const myGameTokenContract = await myGameTokenContractFactory.deploy();

    /*
        .deployed() is here apparently to ensure that the transaction is mined,
        altough commenting it out doesn't seem to affect anything. This might
        be due to how Hardhat processed and mines transactions? (Feb 16 '23 -Jed).
        from https://docs.ethers.org/v4/api-contract.html#deployment
            Keep in mind that the Contract may not be mined immediately.
            The contract.deployed() function will return a Promise which will resolve once the contract is deployed,
            or reject if there was an error during deployment.
    */
    await myGameTokenContract.deployed();

    return myGameTokenContract;

    // We also save the contract's artifacts and address in the frontend directory
    //   saveFrontendFiles(token);
}

deployContract()
    .then(async (deployedContract) => {
        console.log("\n***** CONTRACT DEPLOYED SUCCESSFULLY *****");
        console.log(`${await deployedContract.name()}                      <- Contract name`);
        console.log(`${deployedContract.address} <- Deployment address`);
        console.log(`${deployedContract.signer.address} <- Deployer address`);

        process.exit(0);
    })
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });

// TODO this is saved from the hardhat-boilerplate tutorial for reference
// function saveFrontendFiles(token) {
//     const fs = require("fs");
//     const contractsDir = path.join(__dirname, "..", "frontend", "src", "contracts");

//     if (!fs.existsSync(contractsDir)) {
//         fs.mkdirSync(contractsDir);
//     }

//     fs.writeFileSync(
//         path.join(contractsDir, "contract-address.json"),
//         JSON.stringify({ Token: token.address }, undefined, 2)
//     );

//     const TokenArtifact = artifacts.readArtifactSync("Token");

//     fs.writeFileSync(
//         path.join(contractsDir, "Token.json"),
//         JSON.stringify(TokenArtifact, null, 2)
//     );
// }


