import { BET_NAMES } from "./betNames";

export const getBetNameMultiplier = (betName) => {
    switch (betName) {
        case BET_NAMES.STRAIGHT_UP_0:
            return 35;
        case BET_NAMES.STRAIGHT_UP_00:
            return 35;
        case BET_NAMES.STRAIGHT_UP_1:
            return 35;
        case BET_NAMES.STRAIGHT_UP_2:
            return 35;
        case BET_NAMES.STRAIGHT_UP_3:
            return 35;
        case BET_NAMES.STRAIGHT_UP_4:
            return 35;
        case BET_NAMES.STRAIGHT_UP_5:
            return 35;
        case BET_NAMES.STRAIGHT_UP_6:
            return 35;
        case BET_NAMES.STRAIGHT_UP_7:
            return 35;
        case BET_NAMES.STRAIGHT_UP_8:
            return 35;
        case BET_NAMES.STRAIGHT_UP_9:
            return 35;
        case BET_NAMES.STRAIGHT_UP_10:
            return 35;
        case BET_NAMES.STRAIGHT_UP_11:
            return 35;
        case BET_NAMES.STRAIGHT_UP_12:
            return 35;
        case BET_NAMES.STRAIGHT_UP_13:
            return 35;
        case BET_NAMES.STRAIGHT_UP_14:
            return 35;
        case BET_NAMES.STRAIGHT_UP_15:
            return 35;
        case BET_NAMES.STRAIGHT_UP_16:
            return 35;
        case BET_NAMES.STRAIGHT_UP_17:
            return 35;
        case BET_NAMES.STRAIGHT_UP_18:
            return 35;
        case BET_NAMES.STRAIGHT_UP_19:
            return 35;
        case BET_NAMES.STRAIGHT_UP_20:
            return 35;
        case BET_NAMES.STRAIGHT_UP_21:
            return 35;
        case BET_NAMES.STRAIGHT_UP_22:
            return 35;
        case BET_NAMES.STRAIGHT_UP_23:
            return 35;
        case BET_NAMES.STRAIGHT_UP_24:
            return 35;
        case BET_NAMES.STRAIGHT_UP_25:
            return 35;
        case BET_NAMES.STRAIGHT_UP_26:
            return 35;
        case BET_NAMES.STRAIGHT_UP_27:
            return 35;
        case BET_NAMES.STRAIGHT_UP_28:
            return 35;
        case BET_NAMES.STRAIGHT_UP_29:
            return 35;
        case BET_NAMES.STRAIGHT_UP_30:
            return 35;
        case BET_NAMES.STRAIGHT_UP_31:
            return 35;
        case BET_NAMES.STRAIGHT_UP_32:
            return 35;
        case BET_NAMES.STRAIGHT_UP_33:
            return 35;
        case BET_NAMES.STRAIGHT_UP_34:
            return 35;
        case BET_NAMES.STRAIGHT_UP_35:
            return 35;
        case BET_NAMES.STRAIGHT_UP_36:
            return 35;
        case BET_NAMES.FIRST_DOZEN:
            return 2;
        case BET_NAMES.SECOND_DOZEN:
            return 2;
        case BET_NAMES.THIRD_DOZEN:
            return 2;
        case BET_NAMES.FIRST_COLUMN:
            return 2;
        case BET_NAMES.SECOND_COLUMN:
            return 2;
        case BET_NAMES.THIRD_COLUMN:
            return 2;
        case BET_NAMES.FIRST_18:
            return 1;
        case BET_NAMES.SECOND_18:
            return 1;
        case BET_NAMES.EVEN:
            return 1;
        case BET_NAMES.ODD:
            return 1;
        case BET_NAMES.RED:
            return 1;
        case BET_NAMES.BLACK:
            return 1;
        default:
            throw new Error("Invalid bet name", betName);
    } 
}
